### PR TITLE
Use % to partition

### PR DESCRIPTION
**Pull request by zhuochun**

### CODE REVIEW

**Comment by xinan** [comment]
LGTM :smile:

**Comment by yangshun** [comment]
Was wondering how @xinan can comment, then realized this is a public repo. :scream:

**Comment by xinan** [comment]
Yeah we made that public so that it can be easily installed as a gem :no_mouth: :trollface:

**Comment by yangshun** [comment]
I can update your comments :trollface:

**Comment by zhuochun** [comment]
@xinan git blame is you didn't fix it :trollface: bb5eae51

**Comment by xinan** [comment]
:crying_cat_face: I thought that was the requirement at that moment

**Pull request closed without merging**
